# Generated by Django 6.0.5 on 2026-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
